name: AbroadEduIndia CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name:  Checkout code
      uses: actions/checkout@v4

    - name:  Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name:  Install dependencies
      run: npm ci

    - name:  Build project (if needed)
      run: npm run build --if-present

    - name:  Run tests (if you have tests)
      run: npm test

    - name:  Upload coverage reports (optional)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
